Bomberman
mate-academy/py-bomberman-one pull request #1
Opened 2022-02-14 12:43 UTC by MasterpieceElbow

2022-02-14 13:41 UTC, IvanRamyk requested changes

2022-02-14 13:41 UTC, IvanRamyk commented on README.md
> +- Replace simple colored rectangles with pictures given in `"app/images/`.
Is there information about how to change the sprite image based on the direction?

2022-02-15 13:54 UTC, IvanRamyk requested changes
I'd recommend using Grammarly to check simple grammar mistakes

2022-02-15 13:54 UTC, IvanRamyk commented on README.md
> +Games! Games is perfect example to show OOP principles at work.
```suggestion
Games! Game is a perfect example to show OOP principles at work.
```

2022-02-15 13:54 UTC, IvanRamyk commented on README.md
> +you have to write your own a little modified version.
```suggestion
it's time to write your own a little modified version.
```
Sounds more friendly for me

2022-02-15 13:54 UTC, IvanRamyk commented on README.md
> +You already have initial structure of game Bomberman.
```suggestion
You already have the initial structure of the game Bomberman.
```

2022-02-15 15:00 UTC, IvanRamyk requested changes

2022-02-15 15:03 UTC, MasterpieceElbow commented on README.md
> +you have to write your own a little modified version.
It is already changed. 0_o

2022-02-15 15:39 UTC, IvanRamyk requested changes

2022-02-15 15:40 UTC, MasterpieceElbow commented on app/main.py
> +        self.width = 50
@IvanRamyk Done

2022-02-16 07:59 UTC, merged